In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/train.csv',usecols=['Age','Fare','Survived'])
df.describe()

         Survived         Age        Fare
count  891.000000  714.000000  891.000000
mean     0.383838   29.699118   32.204208
std      0.486592   14.526497   49.693429
min      0.000000    0.420000    0.000000
25%      0.000000   20.125000    7.910400
50%      0.000000   28.000000   14.454200
75%      1.000000   38.000000   31.000000
max      1.000000   80.000000  512.329200

In [4]:
df.dropna(inplace=True)

In [5]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [6]:
df.sample(5)

     Survived   Age     Fare
751         1   6.0  12.4750
786         1  18.0   7.4958
628         0  26.0   7.8958
3           1  35.0  53.1000
696         0  44.0   8.0500

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size = 0.1)
x_train

      Age     Fare
262  52.0  79.6500
641  24.0  69.3000
346  40.0  13.0000
94   59.0   7.2500
827   1.0  37.0042
..    ...      ...
357  38.0  13.0000
642   2.0  27.9000
91   20.0   7.8542
818  43.0   6.4500
844  17.0   8.6625

[642 rows x 2 columns]

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf = DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.5833333333333334

In [12]:
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer
def discretization(bins,strategy):
  k_bin_age = KBinsDiscretizer(n_bins=bins,encode='ordinal',strategy=strategy)
  k_bin_fare = KBinsDiscretizer(n_bins=bins,encode='ordinal',strategy=strategy)

  tf = ColumnTransformer([
      ('first',k_bin_age,[0]),
      ('second',k_bin_fare,[1])
  ])
  x_train_trf=tf.fit_transform(x_train)
  x_test_trf=tf.transform(x_test)

  clf.fit(x_train_trf,y_train)
  y_pred1=clf.predict(x_test_trf)
  c = accuracy_score(y_test,y_pred1)
  print(c)

In [13]:
discretization(10,'quantile')

0.6805555555555556