<a href="https://colab.research.google.com/github/kartik-tiwariR20/100daysofml/blob/main/CCAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('/content/data_science_job.csv')
df.sample(10)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
4750,23772,city_28,0.939,Male,Has relevent experience,no_enrollment,Graduate,STEM,11.0,50-99,Pvt Ltd,6.0,0.0
11844,26381,city_28,0.939,Male,No relevent experience,no_enrollment,Graduate,STEM,10.0,NaN,NaN,12.0,0.0
7250,22203,city_103,0.920,Male,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,Other,5.0,0.0
17698,3641,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,100-500,Pvt Ltd,192.0,0.0
15479,26524,city_75,0.939,Male,No relevent experience,Part time course,Graduate,STEM,20.0,50-99,Pvt Ltd,122.0,0.0
18870,16045,city_103,0.920,NaN,Has relevent experience,Full time course,Graduate,STEM,16.0,50-99,NaN,23.0,1.0
6398,6646,city_136,0.897,Male,Has relevent experience,Part time course,Graduate,STEM,10.0,10000+,Pvt Ltd,26.0,0.0
1867,14572,city_21,0.624,Male,Has relevent experience,no_enrollment,Masters,STEM,8.0,50-99,Public Sector,33.0,1.0
11138,1847,city_103,0.920,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,10/49,Pvt Ltd,63.0,0.0
17569,14036,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,8.0,50-99,Funded Startup,6.0,0.0

In [13]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index     479
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
training_hours             766
target                       0
dtype: int64

In [14]:
df.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

5% se kam jo jo hai usi mai cca lgana chahiye

In [17]:
df.dropna(subset=['experience'], inplace=True)

In [18]:
df['experience'].isnull().sum()
# Now, this should show 0 null values for 'experience'

np.int64(0)

In [19]:
df.dropna(subset=['training_hours'], inplace=True)
df.dropna(subset=['city_development_index'], inplace=True)

In [20]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4162
relevent_experience          0
enrolled_university        356
education_level            415
major_discipline          2621
experience                   0
company_size              5534
company_type              5708
training_hours               0
target                       0
dtype: int64