In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [21]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('has_covid',axis = 1),df['has_covid'],test_size = 0.1)
x_train.sample(5)

    age  gender  fever   cough       city
40   49  Female  102.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
79   48  Female  103.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
60   24  Female  102.0  Strong  Bangalore

In [23]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers = [
    ('tf1' , SimpleImputer(),['fever']),
    ('tf2' , OneHotEncoder(drop= 'first',sparse_output= False),['gender','city']),
    ('tf3' , OrdinalEncoder(categories = [['Mild','Strong']]),['cough'])
] , remainder='passthrough')
transformer.fit_transform(x_train)

array([[101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [103.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  46.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  55.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.75308642,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  51.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  11.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  17.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  56.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  50.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  66.        ],
       [102.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  71.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [100.75308642,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  75.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  51.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ],
       [ 99.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  25.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  24.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  31.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [100.75308642,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  82.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  82.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  14.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  48.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,   5.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [100.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  13.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   8.        ],
       [100.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  27.        ],
       [100.75308642,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  75.        ],
       [100.75308642,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  20.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  40.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  70.        ],
       [104.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  54.        ],
       [103.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  60.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  16.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  65.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  81.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  81.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  23.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  69.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  47.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  44.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  74.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  12.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [100.75308642,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  71.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  68.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  65.        ],
       [100.75308642,   1.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  79.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  24.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  83.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  15.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  10.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   1.        ,  82.        ],
       [100.75308642,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [100.75308642,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  23.        ]])