In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import FunctionTransformer

In [17]:
df = pd.read_csv('/content/train.csv',usecols=['Age','Fare','Survived'])
df.sample(5)

     Survived   Age     Fare
508         0  28.0  22.5250
798         0  30.0   7.2292
676         0  24.5   8.0500
430         1  28.0  26.5500
159         0   NaN  69.5500

In [18]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [19]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipykernel_5162/694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [20]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [21]:
df['Age'].skew()

np.float64(0.4344880940129925)

In [22]:
df['Fare'].skew()

np.float64(4.787316519674893)

FARE IS RIGHT SKEWED AND AGE IS NORMALLY DISTRIBUTED

In [23]:
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survived',axis = 1),df['Survived'],test_size=0.1,random_state=42)
x_train

           Age      Fare
165   9.000000   20.5250
541   9.000000   31.2750
625  61.000000   32.3208
388  29.699118    7.7292
76   29.699118    7.8958
..         ...       ...
106  21.000000    7.6500
270  29.699118   31.0000
860  41.000000   14.1083
435  14.000000  120.0000
102  21.000000   77.2875

[801 rows x 2 columns]

In [24]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

print("LR",accuracy_score(y_test,y_pred1))
print("DT",accuracy_score(y_test,y_pred2))

LR 0.6666666666666666
DT 0.6555555555555556

In [27]:
tf1 = ColumnTransformer([
    ('log',FunctionTransformer(np.log1p),['Fare'])
], remainder='passthrough')

x_train_transformed = tf1.fit_transform(x_train)
x_test_transformed = tf1.transform(x_test)

In [28]:
clf1.fit(x_train_transformed,y_train)
clf2.fit(x_train_transformed,y_train)

y_pred_trans1 = clf1.predict(x_test_transformed)
y_pred_trans2 = clf2.predict(x_test_transformed)

print("LR",accuracy_score(y_test,y_pred_trans1))
print("DT",accuracy_score(y_test,y_pred_trans2))

LR 0.6888888888888889
DT 0.6444444444444445

IMPROVE HOGYA HAI