In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_csv('/content/train.csv',usecols = ['Age','Fare','Survived','Pclass'])
df.sample(10)

     Survived  Pclass   Age      Fare
400         1       3  39.0    7.9250
449         1       1  52.0   30.5000
680         0       3   NaN    8.1375
195         1       1  58.0  146.5208
561         0       3  40.0    7.8958
883         0       2  28.0   10.5000
102         0       1  21.0   77.2875
661         0       3  40.0    7.2250
0           0       3  22.0    7.2500
406         0       3  51.0    7.7500

In [25]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survived',axis=1),df['Survived'],test_size=0.1)
x_train

     Pclass   Age     Fare
773       3   NaN   7.2250
153       3  40.5  14.5000
515       1  47.0  34.0208
161       2  40.0  15.7500
503       3  37.0   9.5875
..      ...   ...      ...
562       2  28.0  13.5000
849       1   NaN  89.1042
329       1  16.0  57.9792
432       2  42.0  26.0000
789       1  46.0  79.2000

[801 rows x 3 columns]

In [27]:
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.compose import ColumnTransformer
knn = KNNImputer(weights='distance',n_neighbors=2)
si = SimpleImputer(strategy='mean')
trf = ColumnTransformer([
    ('age_imputed',si,['Age'])
],remainder='passthrough')
x_train1 = knn.fit_transform(x_train)
x_train2 = trf.fit_transform(x_train)
x_test1 = knn.transform(x_test)
x_test2 = trf.transform(x_test)

In [28]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train1,y_train)
lr.fit(x_train2,y_train)

y_pred1 = lr.predict(x_test1)
y_pred2 = lr.predict(x_test2)

In [29]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred1))
print(accuracy_score(y_test,y_pred2))

0.6555555555555556
0.7222222222222222