<a href="https://colab.research.google.com/github/kartik-tiwariR20/100daysofml/blob/main/making_own_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
class LinearRegression :

  def __init__(self):
    self.m = None
    self.b = None

  def fit(self,X_train,y_train):

    num = 0
    den = 0

    for i in range(X_train.shape[0]):
      num = num + ((x_train.values[i] - x_train.mean()) * (y_train.values[i] - y_train.mean()))
      den = den + ((x_train.values[i] - x_train.mean()) * (x_train.values[i] - x_train.mean()))

    self.m = num/den
    self.b = y_train.mean() - (self.m * x_train.mean())
    print("m is ",self.m)
    print("b is ",self.b)

  def predict(self,x_test):
   return (self.m * x_test) + self.b

In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('/content/placementttt.csv')
df.sample(1)

     cgpa  package
128  7.93     3.34

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('package',axis=1),df['package'],test_size=0.1,random_state =2)
y_test

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
Name: package, dtype: float64

In [40]:
x_test.shape

(20, 1)

In [41]:
x_train.values[1]

array([7.28])

In [42]:
lr = LinearRegression()
lr.fit(x_train,y_train)

m is  cgpa    0.564769
dtype: float64
b is  cgpa   -0.952233
dtype: float64

In [43]:
for i in range(x_test.shape[0]):
  print(lr.predict(x_test.values[i]))

cgpa    3.893486
dtype: float64
cgpa    3.085866
dtype: float64
cgpa    2.36861
dtype: float64
cgpa    2.560631
dtype: float64
cgpa    1.628762
dtype: float64
cgpa    1.753011
dtype: float64
cgpa    2.052339
dtype: float64
cgpa    2.922083
dtype: float64
cgpa    3.763589
dtype: float64
cgpa    2.927731
dtype: float64
cgpa    4.096803
dtype: float64
cgpa    3.509443
dtype: float64
cgpa    2.961617
dtype: float64
cgpa    2.385553
dtype: float64
cgpa    3.181877
dtype: float64
cgpa    3.464262
dtype: float64
cgpa    1.922442
dtype: float64
cgpa    3.238354
dtype: float64
cgpa    2.967265
dtype: float64
cgpa    3.413433
dtype: float64