<a href="https://colab.research.google.com/github/kartik-tiwariR20/100daysofml/blob/main/mean_median_imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv('/content/titanic_toy.csv')
df.sample(5)

      Age     Fare  Family  Survived
153  40.5  14.5000       2         0
507   NaN  26.5500       0         1
239  33.0  12.2750       0         0
322  30.0  12.3500       0         1
8    27.0  11.1333       2         1

In [29]:
df.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [30]:
df['age_mean']=df['Age'].fillna(df['Age'].mean())
df['age_median']=df['Age'].fillna(df['Age'].median())
df['fare_mean']=df['Fare'].fillna(df['Fare'].mean())
df['Fare_mean']=df['Fare'].fillna(df['Fare'].median())

In [31]:
df.head()

    Age     Fare  Family  Survived  age_mean  age_median  fare_mean  Fare_mean
0  22.0   7.2500       1         0      22.0        22.0     7.2500     7.2500
1  38.0  71.2833       1         1      38.0        38.0    71.2833    71.2833
2  26.0   7.9250       0         1      26.0        26.0     7.9250     7.9250
3  35.0  53.1000       1         1      35.0        35.0    53.1000    53.1000
4  35.0   8.0500       0         0      35.0        35.0     8.0500     8.0500

In [32]:
df['Fare'].var()

2530.6730768999487

In [33]:
df['fare_mean'].var()

2402.717696607255

In [34]:
sm = pd.read_csv('/content/titanic_toy.csv')

SKLEARN SE KARTE HAI

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(sm.drop('Survived',axis=1),sm['Survived'],test_size=0.1)
x_train

      Age      Fare  Family
247  24.0   14.5000       2
7     2.0   21.0750       4
204  18.0    8.0500       0
740   NaN   30.0000       0
512  36.0   26.2875       0
..    ...       ...     ...
425   NaN    7.2500       0
238  19.0   10.5000       0
507   NaN   26.5500       0
849   NaN   89.1042       1
393  23.0  113.2750       1

[801 rows x 3 columns]

In [36]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([
    ('imputer1',SimpleImputer(strategy='mean'),['Age']),
    ('imputer2',SimpleImputer(strategy='mean'),['Fare'])
],remainder='passthrough')

In [37]:
x_train=ct.fit_transform(x_train)
x_test=ct.transform(x_test)