In [25]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/cars.csv')
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [26]:
pd.get_dummies(df,columns = ['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('selling_price',axis=1),df['selling_price'],test_size=0.1)
x_train.head(5)

       brand  km_driven    fuel        owner
1855    Tata     100000  Diesel  First Owner
4886    Tata      22000  Petrol  First Owner
1066  Toyota      43000  Diesel  First Owner
559     Ford      14200  Petrol  First Owner
6579  Maruti      58343  Petrol  First Owner

In [28]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first' , dtype = np.int32)
x_train_new = ohe.fit_transform(x_train[['fuel','owner']]).toarray()
x_test_new = ohe.transform(x_test[['fuel','owner']]).toarray()
x_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1]], dtype=int32)

In [29]:
np.hstack((x_train[['brand','km_driven']].values, x_train_new))

array([['Tata', 100000, 1, ..., 0, 0, 0],
       ['Tata', 22000, 0, ..., 0, 0, 0],
       ['Toyota', 43000, 1, ..., 0, 0, 0],
       ...,
       ['Volkswagen', 60000, 0, ..., 1, 0, 0],
       ['Toyota', 45000, 1, ..., 0, 0, 0],
       ['Hyundai', 35000, 0, ..., 0, 0, 1]], dtype=object)

In [30]:
counts = df['brand'].value_counts()
df['brand'].nunique()
threshold = 100
repl = counts[counts <= threshold].index
pd.get_dummies(pd.Series(df['brand'].replace(repl,'uncommon')))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False