In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv('/content/customer.csv')
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
22   18  Female     Poor        PG       Yes
10   98  Female     Good        UG       Yes
3    72  Female     Good        PG        No
32   92    Male  Average        UG       Yes

In [21]:
df = df.iloc[:,2:]
df.sample(5)

   review education purchased
41   Good        PG       Yes
27   Poor        PG        No
6    Good    School        No
15   Poor        UG        No
9    Good        UG       Yes

In [22]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)
x_train.sample(5),x_test.sample(5)

(     review education
 37  Average        PG
 7      Poor    School
 12     Poor    School
 45     Poor        PG
 10     Good        UG,
      review education
 46     Poor        PG
 15     Poor        UG
 29  Average        UG
 30  Average        UG
 27     Poor        PG)

In [23]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
x_train = oe.fit_transform(x_train[['review','education']])
x_test = oe.transform(x_test[['review','education']])

In [24]:
x_train

array([[2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [2., 0.],
       [2., 1.]])

In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [26]:
y_train

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1])