In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/concrete_data.csv')
df.sample(5)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
387,520.0,0.0,0.0,175.0,5.2,870.0,805.0,28,51.02
570,295.8,0.0,0.0,185.7,0.0,1091.4,769.3,28,25.22
113,389.9,189.0,0.0,145.9,22.0,944.7,755.8,7,59.09
841,305.0,0.0,100.0,196.0,10.0,959.0,705.0,28,30.12
660,116.0,173.0,0.0,192.0,0.0,909.8,891.9,90,31.02

In [7]:
df.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [8]:
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [10]:
from sklearn.model_selection import train_test_split,cross_val_score
x_train,x_test,y_train,y_test = train_test_split(df.drop('Strength',axis=1),df['Strength'],test_size=0.1,random_state=42)
y_train

806    24.00
168    70.70
590    10.34
464    56.81
998    30.12
       ...
87     24.40
330    42.22
466    33.56
121    68.30
860    38.46
Name: Strength, Length: 927, dtype: float64

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
r2_score(y_test,y_pred)

0.6196312800273646

In [12]:
np.mean(cross_val_score(lr,df.drop('Strength',axis=1),df['Strength'],scoring = 'r2'))

np.float64(0.46099404916628606)

In [17]:
from sklearn.preprocessing import PowerTransformer
ft = PowerTransformer(method='yeo-johnson')
x_train_transformed = ft.fit_transform(x_train)
x_test_transformed = ft.transform(x_test)
pd.DataFrame({'cols' : x_train.columns,'yeo-johnson_lambdas' : ft.lambdas_})

                 cols  yeo-johnson_lambdas
0              Cement             0.173931
1  Blast Furnace Slag             0.012297
2             Fly Ash            -0.138135
3               Water             0.791064
4    Superplasticizer             0.274860
5    Coarse Aggregate             1.179360
6      Fine Aggregate             1.808138
7                 Age             0.011261

In [19]:
lr.fit(x_train_transformed,y_train)
y_pred1 = lr.predict(x_test_transformed)
r2_score(y_test,y_pred1)

0.8313170749617695

In [20]:
np.mean(cross_val_score(lr,x_train_transformed,y_train,scoring = 'r2'))

np.float64(0.7980678319172754)

PERFECT