In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/placement.csv')

In [4]:
df.shape

(100, 4)

In [6]:
df.head(5)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [7]:
df.sample(5)

    Unnamed: 0  cgpa     iq  placement
9            9   5.1   66.0          0
35          35   6.8   90.0          1
85          85   5.8  166.0          1
64          64   7.0   64.0          1
29          29   7.0  112.0          1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [10]:
df.notnull().sum()

Unnamed: 0    100
cgpa          100
iq            100
placement     100
dtype: int64

In [11]:
df.describe()

       Unnamed: 0        cgpa          iq   placement
count  100.000000  100.000000  100.000000  100.000000
mean    49.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      0.000000    3.300000   37.000000    0.000000
25%     24.750000    5.075000  101.500000    0.000000
50%     49.500000    6.000000  127.500000    0.500000
75%     74.250000    6.900000  149.000000    1.000000
max     99.000000    8.500000  233.000000    1.000000

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.corr()

            Unnamed: 0      cgpa        iq  placement
Unnamed: 0    1.000000  0.047478 -0.019080   0.144807
cgpa          0.047478  1.000000 -0.098791   0.821688
iq           -0.019080 -0.098791  1.000000  -0.083031
placement     0.144807  0.821688 -0.083031   1.000000

In [14]:
df.corr()['iq']

Unnamed: 0   -0.019080
cgpa         -0.098791
iq            1.000000
placement    -0.083031
Name: iq, dtype: float64