In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/placement123.csv')
df.sample(10)

     cgpa  placement_exam_marks  placed
317  7.47                  19.0       0
940  6.16                  38.0       0
124  6.20                  30.0       0
489  7.24                  50.0       0
167  6.65                  48.0       1
651  6.57                  39.0       1
297  7.03                  32.0       1
719  7.17                  26.0       0
161  6.26                  52.0       1
700  6.82                  16.0       1

In [3]:
df['cgpa'].skew()

np.float64(-0.014529938929314918)

In [4]:
df['placement_exam_marks'].skew()

np.float64(0.8356419499466834)

In [5]:
upper_limit = df['cgpa'].mean() + 3*df['cgpa'].std()
lower_limit = df['cgpa'].mean() - 3*df['cgpa'].std()
print(upper_limit)
print(lower_limit)

8.808933625397168
5.113546374602832

In [6]:
df[(df['cgpa']>upper_limit) | (df['cgpa']<lower_limit)]

     cgpa  placement_exam_marks  placed
485  4.92                  44.0       1
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
999  4.90                  10.0       1

TRIMMING

In [10]:
new_df = df[(df['cgpa']<upper_limit) & (df['cgpa']>lower_limit)]
new_df

     cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
4    7.23                  17.0       0
..    ...                   ...     ...
991  7.04                  57.0       0
992  6.26                  12.0       0
993  6.73                  21.0       1
994  6.48                  63.0       0
998  8.62                  46.0       1

[995 rows x 3 columns]

CAPPING

In [14]:
df['cgpa'] = np.where(
    df['cgpa']>upper_limit,
    upper_limit,
    np.where(df['cgpa']<lower_limit,
    lower_limit,
    df['cgpa']
)
)

In [17]:
df.shape

(1000, 3)